### ISSUE TITLE
CREATE PROJECT DIRECTORY AND FILES FOR PROJECT

### ISSUE THREAD

**Issue by mrozenbaum** [EducatedCamels/educated_camels#10]
### Task
---
(detailed overview)
Create project directory for 'BANGAZON_API' and the files that will be used in the project.

### Context
---
(Reasoning for this ticket)

### Before starting ticket
---
(Software needed and docs to reference)
### BEFORE STARTING PROJECT
---
- [ ] read the README
- [ ] read the Django Documentation
- [ ] read the DjangoREST Frame work.
- [ ] reviewed the [ISSUES](https://github.com/EducatedCamels/educated_camels/issues)(open and closed) to make sure my issue hasn't already been resolved, and that this ticket is not a duplicate.
- [ ] verified I'm using an account with administrative privileges.
- [ ] i have Django installed on my machine
- [ ] i have DjangoREST installed on my machine

[Django](https://www.djangoproject.com/rl)
[Django REST](http://www.django-rest-framework.org/)

### The process 
---
- [ ] Create a Main Project Directory Label: 'Bangazon_Api_Project'
- [ ] Create file 'manage.py' inside 'Bangazon_Api_Project' directory.
- [ ] Create directory labeled 'BangazonAPI' inside 'Bangazon_Api_Project' directory
 Bangazon_Api_Project/BangazonAPI
- [ ] Create 'Templates' directory with 'details.html' Bangazon_Api_Project/BangazonAPI/Templates/details.html
- [ ] Create Inside 'Templates' directory an 'index.html file Bangazon_Api_Project/BangazonAPI/Templates/index.html
- [ ] Create Inside 'Templates' directory a 'results.html' file Bangazon_Api_Project/BangazonAPI/Templates/results.html

### Outcome/expected behavior
---

### Other related tickets
---
