### ISSUE TITLE
Expose Order Data 

### ISSUE THREAD

**Issue by briwyatt** [EducatedCamels/educated_camels#11]
### Task
---
To create an Order Object Class for our Database via Django REST Framework. The Objective of this task is to expose Order data for the client.

### Context
---
An Employee class table is required for the integrity of the database. It provides a primary key that links to two different tables(Employee_In_Training_Program, Employee_Gets_Computer) and a foreign key(Department_Id property) that links to one table(Department). Please refer to the ERD table:[ERD](https://www.draw.io/?state=%7B%22ids%22:%5B%220B-4vZ-mgQ31vc2cxUVVOamFFU2c%22%5D,%22action%22:%22open%22,%22userId%22:%22100761558679069137145%22%7D#G0B-4vZ-mgQ31vc2cxUVVOamFFU2c)

- For more resources on this projects click [Here](https://github.com/EducatedCamels/educated_camels/blob/master/resources/resources.md)

### The process 
---
- [ ] Pull Down Bangazon Project onto your local computer and create a new git branch

-  [ ] Go to the Bangazon directory 

- [ ] Go to the API app

- [ ] Create the Order Class in the models.py file with the properties required: Order_ID(PK), Customer_ID(FK), Payment_Type_ID(FK), Date_Created(FK).

- [ ] Create an Order viewset in the views.py file.

-  [ ] Create a class that displays the specific attributes of the Order class in the serializers.py file 

- [ ] add the employee class url extension "/order" in the urls.py file

### Outcome/expected behavior
---
 In all, 4 files will be changed. After these changes, the Class created will be ready to migrate using the Django REST framework. The outcome of the migrated files will expose the Order Class that can also be linked to the other data tables in the database.
