### ISSUE TITLE
Expose Customer Data

### ISSUE THREAD

**Issue by sarawithad** [EducatedCamels/educated_camels#12]
### Task
---
Create a Customer Class for our Database via Django REST Framework. The Objective of this task is to expose customer data for the client.

### Context
---
An Employee class table is required for the integrity of the database. Review ERD for more information.

- For more resources on this products click [Here](https://github.com/EducatedCamels/educated_camels/blob/master/resources/resources.md)

### The process 
---
- [ ] Pull Down Bangazon Project onto your local computer and create a new git branch

-  [ ] Go to the Bangazon directory 

- [ ] Go to the API app

- [ ] Create the Customer Class in the models.py file with the properties listed on ERD.

- [ ] Create a viewset Class for the Customer Class in the views.py file.

-  [ ] Create a class that displays the specific attributes of the Customer class in the serializers.py file 

- [ ] Add the employee class url extension "/customers" in the urls.py file

### Outcome/expected behavior
---
In all, 4 files will be changed. After these changes, the Class created will be ready to migrate using the Django REST framework. The outcome of the migrated files will expose the Employee Class that can also be linked to the other data tables in the database.
