### ISSUE TITLE
Expose Training Program Data

### ISSUE THREAD

**Issue by harryepstein** [EducatedCamels/educated_camels#14]
### Task
---
To create an Training Program Class for our Database via Django REST Framework. The Objective of this task is to expose Training Program data for the client.
### Context
---

An Training Program class table is required for the integrity of the database. It provides a foreign key(Department_Id property) that links to one table(Employees_In_Training_Program). 

Please refer to the ERD table for further information:[ERD](https://www.draw.io/?state=%7B%22ids%22:%5B%220B-4vZ-mgQ31vc2cxUVVOamFFU2c%22%5D,%22action%22:%22open%22,%22userId%22:%22100761558679069137145%22%7D#G0B-4vZ-mgQ31vc2cxUVVOamFFU2c)

- For more resources on this prodects click [Here](https://github.com/EducatedCamels/educated_camels/blob/master/resources/resources.md)

### The process 
---
- [ ] Pull Down Bangazon Project onto your local computer and create a new git branch

-  [ ] Go to the Bangazon directory 

- [ ] Go to the API app

- [ ] Create the Training Program Class in the models.py file with the properties required: Training Program_ID(PK), Start_Date. End_Date, Max_Attendees, and Program_Title

- [ ] Create a viewset Class for the Training Program Table in the views.py file.

-  [ ] Create a class that displays the specific attributes of the Training Program class in the serializers.py file 

- [ ] add the Training Program class url extension "/Training Program" in the urls.py file

### Outcome/expected behavior
---
 In all, 4 files will be changed. After these changes, the Class created will be ready to migrate using the Django REST framework. The outcome of the migrated files will expose the Training Program Class that can also be linked to the other data tables in the database.
