### ISSUE TITLE
Expose Payment Types Data

### ISSUE THREAD

**Issue by sarawithad** [EducatedCamels/educated_camels#15]
### Task
---
To create a Payment_Type Object Class for our Database via Django REST Framework. The Objective of this task is to expose product type data for the client.

### Context
---
A Payment_Type Class table is required for the integrity of the database. Please refer to the ERD table: [ERD](https://github.com/EducatedCamels/educated_camels/blob/master/resources/resources.md)

- For more resources on this projects click [Here](https://github.com/EducatedCamels/educated_camels/blob/master/resources/resources.md)

### The process 
---
- [ ] Pull Down Bangazon Project onto your local computer and create a new git branch

-  [ ] Go to the Bangazon directory 

- [ ] Go to the API app

- [ ] Create the Payment_Type Class in the models.py file with the required properties.

- [ ] Create a viewset Class for the Payment_Type model in the views.py file.

-  [ ] Create a class that displays the specific attributes of the Product_Type class in the serializers.py file 

- [ ] Add the employee class url extension "/paymenttypes" in the urls.py file

### Outcome/expected behavior
---
 In all, 4 files will be changed. After these changes, the Class created will be ready to migrate using the Django REST framework. The outcome of the migrated files will expose the Employee Class that can also be linked to the other data tables in the database. 

### Other related tickets
---
- Expose Payment Data
