### ISSUE TITLE
Expose Department Data 

### ISSUE THREAD

**Issue by briwyatt** [EducatedCamels/educated_camels#16]
### Task
---
To create a Department Object Class for our Database via Django REST Framework. The Objective of this task is to expose data for the client.
### Context
---
An Department class table is required for the integrity of the database. It provides a primary key that links to three different tables(Payment_Type, Product_On_Order, Customer) and a foreign key(Department_Id property) that links to one table(Department). Please refer to the ERD table:[ERD](https://www.draw.io/?state=%7B%22ids%22:%5B%220B-4vZ-mgQ31vc2cxUVVOamFFU2c%22%5D,%22action%22:%22open%22,%22userId%22:%22100761558679069137145%22%7D#G0B-4vZ-mgQ31vc2cxUVVOamFFU2c)
- For more resources on this projects click [Here](https://github.com/EducatedCamels/educated_camels/blob/master/resources/resources.md)

### The process 
---
- [ ] Pull Down Bangazon Project onto your local computer and create a new git branch

-  [ ] Go to the Bangazon directory 

- [ ] Go to the API app

- [ ] Create the Department Class in the models.py file with the properties required: Department_ID(PK) , Department_Name, Budget

- [ ] Create a Department viewset in the views.py file.

-  [ ] Create a class that displays the specific attributes of the Department class in the serializers.py file 

- [ ] add the Department class url extension "/department" in the urls.py file

### Outcome/expected behavior
---

In all, 4 files will be changed. After these changes, the Class created will be ready to migrate using the Django REST framework. The outcome of the migrated files will expose the Department Class that can also be linked to the other data tables in the database.
