### ISSUE TITLE
Create Project Directory and Project Files

### ISSUE THREAD

**Issue by mrozenbaum** [EducatedCamels/educated_camels#17]
### Task
---
Our goal is to build the initial, open API for Bangazon as well as expose the resources in our API.

You will need to :
Create a project folder with all needed directories/files for the  Bangazon API Project. 

### Context
---
For the Bangazon API project, you will need to create directories and files that are required to be in a specific structure for the Bangazon API project.
Please Follow the [resources](https://github.com/EducatedCamels/educated_camels/blob/master/resources/resources.mdrl) to see any requirements and expectations for this project.

### The process 
---

- [ ] create the 'Bangazon' directory ('tutorial')
- [ ] cd into the 'Bangazon' directory 
   In the 'Bangazon' directory create the following files:
- [ ]  'manage.py' file
- [ ]  'settings.py' file
- [ ]  'urls.py' file
- [ ]  'wgsi.py' file
- [ ]  '.gitignore' file
- [ ] in the 'Bangazon' directory create a 'API' directory ('quickstart')
- [ ] cd into the  'API' directory
- [ ] in the 'API' directory create a 'migrations' directory ('folder') 
- [ ] cd into the  'migrations' directory
   In the 'migrations' directory create the following files:
- [ ]  '__init__.py' file
- [ ] 'apiconfig.py' file
- [ ] 'models.py' file
- [ ] 'serializers.py' file
- [ ] 'tests.py' file
- [ ] 'views.py' file

### Outcome/expected behavior
---
A well structured project folder with the correct structure of the directories and files.
