### ISSUE TITLE
Expose Departments Class v2

### ISSUE THREAD

**Issue by mrozenbaum** [EducatedCamels/educated_camels#18]
### Task
---

To create a Departments Object Class for our Database via Django REST Framework. 
The Objective of this task is to expose Departments data for the client.

### Context
---

A Department class table is required for the integrity of the database. It provides a primary key (Department_Id) that links to the Employees table foreign key (Department_Id). 

View our projects [Resources](https://github.com/EducatedCamels/educated_camels/blob/master/resources/resources.md)

### The Process 
---

- [ ] Pull Down the Bangazon Project onto your local computer and create a new git branch

-  [ ] cd to the Bangazon directory 

- [ ] cd to the API app

- [ ] Create the Departments Class in the 'models.py' file with the following properties: Department_Id(PK), Budget. 

- [ ] Create a viewset for the Departments Table in the 'views.py' file.

-  [ ] Display the specific attributes of the Departments Class in the 'serializers.py' file 

- [ ] Add the Departments Class url extension '/departments' in the 'urls.py' file

### Outcome/Expected Behavior
---

In total, 4 files will be changed. After these changes, the 'Departments Class' created will be ready to migrate using the Django REST framework. The outcome of the migrated files will expose the Departments Class that can also be linked to the other data tables in the database.
