### ISSUE TITLE
Readme content

### ISSUE THREAD

**Issue by Deanomatic** [EducatedCamels/educated_camels#25]
### Task
---
Adding content to the readme file.
### Context
---
No current resource for outsiders to understand what to do with this project. The readme provides information needed to install and run.

- For more resources on this prodects click [Here]()

### The process 
---
- [ ] Pull Down Bangazon Project onto your local computer and create a new git branch

-  [ ] Go to the Bangazon directory 

- [ ] Add relevant content to readme

### Outcome/expected behavior
---
Only readme file should be changed. This should not effect the functionality.
