### ISSUE TITLE
Expose Employee Data

### ISSUE THREAD

**Issue by briwyatt** [EducatedCamels/educated_camels#3]
### Task
- To create an Employee Object Class for our Database via Django REST Framework. The Objective of this task is to expose Employee data for the client.
---

### Context
- An Employee class table is required for the integrity of the database. It provides a primary key that links to two different tables(Employee_In_Training_Program, Employee_Gets_Computer) and a foreign key(Department_Id property) that links to one table(Department). Please refer to the ERD table: [ERD](https://www.draw.io/?state=%7B%22ids%22:%5B%220B-4vZ-mgQ31vc2cxUVVOamFFU2c%22%5D,%22action%22:%22open%22,%22userId%22:%22100761558679069137145%22%7D#G0B-4vZ-mgQ31vc2cxUVVOamFFU2c)
---

### Process 
-  [ ] Go to the Bangazon directory 

- [ ] Go to the API app

- [ ] Create the Employee Class in the models.py file with the properties required: Employee_ID(PK), DepartmentID(FK). First_Name, Last_Name, Is_Supervisor (True=1, False=0)

- [ ] Create a viewset Class for the Employee Table in the views.py file.

-  [ ] Create a class that displays the specific attributes of the Employee class in the serializers.py file 

- [ ] add the employee class url extension "/employee" in the urls.py file

### In all, 4 files will be changed. After these changes, the Class created will be ready to migrate using the Django REST framework.
---

### Outcome 
- The outcome should expose the Employee Class that can also be linked to the other data tables in the database. 
---

### Other related tickets
- Department Class
- Employee_In_Training_Program Class
- Employee_Gets_Computer Class
---

**Comment by sarawithad** [comment]
So I really like all of what you wrote... 👍
