### ISSUE TITLE
Expose EmployeeTrainingProgram Data

### ISSUE THREAD

**Issue by sarawithad** [EducatedCamels/educated_camels#36]
### Task
---

To create an EmployeeTrainingProgram Object Class for our Database via Django REST Framework. The Objective of this task is to expose EmployeeTrainingProgram data for the client.
### Context
---
EmployeeTrainingProgram class table is required for the integrity of the database.

- For more resources on this project click [Here](https://github.com/EducatedCamels/educated_camels/blob/master/resources/resources.md)

### The process 
---
- [ ] Pull Down Bangazon Project onto your local computer and create a new git branch

-  [ ] Go to the Bangazon directory 

- [ ] Go to the API app

- [ ] Create the EmployeeTrainingProgram Class in the models.py file with the properties required

- [ ] Create a viewset Class for the EmployeeTrainingProgram Table in the views.py file.

-  [ ] Create a class that displays the specific attributes of the EmployeeTrainingProgram class in the serializers.py file 

- [ ] add the EmployeeTrainingProgram class url extension "/employee" in the urls.py file

### Outcome/expected behavior
---
 In all, 4 files will be changed. After these changes, the Class created will be ready to migrate using the Django REST framework. The outcome of the migrated files will expose the EmployeeTrainingProgram Class that can also be linked to the other data tables in the database. 

### Other related tickets
---
Expose TrainingProgram Data
Expose Employee Data
