### ISSUE TITLE
Expose EmployeeComputer Data

### ISSUE THREAD

**Issue by sarawithad** [EducatedCamels/educated_camels#37]
### Task
---

To create an EmployeeComputer Object Class for our Database via Django REST Framework. The Objective of this task is to expose EmployeeComputer data for the client.
### Context
---
EmployeeComputer class table is required for the integrity of the database. Please refer to the ERD table:ERD

- For more resources on this project click [Here](https://github.com/EducatedCamels/educated_camels/blob/master/resources/resources.md)

### The process 
---
- [ ] Pull Down Bangazon Project onto your local computer and create a new git branch

-  [ ] Go to the Bangazon directory 

- [ ] Go to the API app

- [ ] Create the EmployeeComputer Class in the models.py file with the properties required.

- [ ] Create a viewset Class for the EmployeeComputer Table in the views.py file.

-  [ ] Create a class that displays the specific attributes of the EmployeeComputer class in the serializers.py file 

- [ ] add the employee class url extension "/employeecomputer" in the urls.py file

### Outcome/expected behavior
---
 In all, 4 files will be changed. After these changes, the Class created will be ready to migrate using the Django REST framework. The outcome of the migrated files will expose the EmployeeComputer Class that can also be linked to the other data tables in the database. 

### Other related tickets
---
Expose Employee Data
Expose Computer Data
