### ISSUE TITLE
Expose Computer Resource

### ISSUE THREAD

**Issue by Deanomatic** [EducatedCamels/educated_camels#4]
### Task
---
Create new computer resource table
### Context
---
 - No current table to store company computers. The Bangazon API needs to expose data of all company computers. 
- Computer table will effect other files such as 
models.py, views.py, urls.py and serializers.py.

### Before starting ticket
---
- [ ] Read prodject readme
- [ ] We are using Django Rest frame work. Familiarize yourself with this if you aren't already. Click [here](http://www.django-rest-framework.org/) to do so.
- [ ] Install Django and Django Rest Framework

### Process 
---
- [ ] Write new class of Computer in models.py at this file path `\tutorial-rest\tutorial\quickstart\models.py` . 
- [ ] Use Bangazon [ERD](https://www.draw.io/?state=%7B%22ids%22:%5B%220B-4vZ-mgQ31vc2cxUVVOamFFU2c%22%5D,%22action%22:%22open%22,%22userId%22:%22117471280047376077408%22%7D#G0B-4vZ-mgQ31vc2cxUVVOamFFU2c) as a reference to tell you what data should be  in the computer table. 
- [ ] Migrate table to database.
### Outcome/expected behavior
---
- You should now be able to access the Bangazon computer data in the API interface.
- Anyone with access to this API should be able to add thier own data.
### Other related tickets
---
Create Employee table

**Comment by briwyatt** [comment]
will you please show me how to write links correctly over .md files tomorrow when we gather ? Good job overall, as another developer I believe coming from another team I would be able to work with the reference from the ERD table , understand the content , and be able to work off of that 👍
