### ISSUE TITLE
CREATE PROJECT DIRECTORY WITH PROJECT FILES

### ISSUE THREAD

**Issue by mrozenbaum** [EducatedCamels/educated_camels#5]
### TITLE:
---
CREATE PROJECT DIRECTORY WITH FILES

### TICKET NUMBER
---
' ABC-123-666'

### MY ENVIRONMENT 
---
- [x] Windows 7 or below (not truly supported due to EOL)
- [x] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.
 
### DESCRIPTION:
---
Build the initial version of the Bangazon Application Programming Interface. This API will be used by much of the rest of the platform, and by our customers to buy & sell products.

### BEFORE STARTING PROJECT
---
- [ ] read the README
- [ ] read the Django Documentation
- [ ] read the DjangoREST Frame work.
- [ ] reviewed the [ISSUES](https://github.com/EducatedCamels/educated_camels/issues)(open and closed) to make sure my issue hasn't already been resolved, and that this ticket is not a duplicate.
- [ ] verified I'm using an account with administrative privileges.
- [ ] i have Django installed on my machine
- [ ] i have DjangoREST installed on my machine

[Django](https://www.djangoproject.com/rl)
[Django REST](http://www.django-rest-framework.org/)

### TASK AND PROCESS
---
Create file structure based on the example below:

- [ ] Directory - Title - 'Bangazon-Api'
Inside 'Bangazon_Api' Directory create the following files:
- [ ] .gitignore
- [ ] settings.py
- [ ] manage.py
- [ ] urls.py
- [ ] serializers.py
- [ ] customers.py

### RELATED LINKS
---
Github:
[educated_camels](https://github.com/EducatedCamels/educated_camels)
ERD:
[ERD](https://drive.google.com/file/d/0B-4vZ-mgQ31vc2cxUVVOamFFU2c/view)

**Comment by briwyatt** [comment]
I think this is good as an overview for the whole project, but too broad for one ticket.
