### ISSUE TITLE
Create JSON data for Product Type

### ISSUE THREAD

**Issue by sarawithad** [EducatedCamels/educated_camels#54]
### Task
---
To create 10 instances of Product Type data and load into database API

### Context
---
Product Type data is needed to test out our database.

### The process 
---
Example: (Checkbox content will change depending on ticket requirements)
- [ ] Pull Down Bangazon Project onto your local computer and create a new git branch

-  [ ] Go to the Bangazon directory 

- [ ] Go to the API app

- [ ] Go to Fixtures folder and add Product Type data to productType.json file

- [ ] Load data from productType.json into database API

### Outcome/expected behavior
---
Product Type data should be available to view in the database
