### ISSUE TITLE
Adding data to computer table in API

### ISSUE THREAD

**Issue by Deanomatic** [EducatedCamels/educated_camels#56]
### Task
---
Creating json for computer table

### Context
---
There is no data in the computer table. The company wants to actually expose some content. This will accomplish that.

### The process 
---
- [ ] Add json data to computer.json inside of the fixtures folder

-  [ ] Make sure you specify the title of the model you want to add to in the json. Here is an example `“model”: “API.Computer”,`

- [ ] Ten different instances of the Computer data are required.

- [ ] Once json is complete type `python manage.py loaddata computer.json` 

- [ ] Once you've loaded data check to see if it is in the API

### Outcome/expected behavior
---
Should expose newly loaded data in the API interface. There should be 10 different computer instances in the computer table.
