### ISSUE TITLE
Adding employee data to API

### ISSUE THREAD

**Issue by Deanomatic** [EducatedCamels/educated_camels#57]
### Task
---
Creating json for employee table

### Context
---
There is no data in the employee table. The company wants to actually expose some real content. This will accomplish that.

### The process 
---
- [ ] Add json data to employee.json inside of the fixtures folder

-  [ ] Make sure you specify the title of the model you want to add to in the json. Here is an example `“model”: “API.employee”,`

- [ ] Ten different instances of the employee data are required.

- [ ] Once json is complete type `python manage.py loaddata employee.json` 

- [ ] Once you've loaded data check to see if it is in the API

### Outcome/expected behavior
---
Should expose newly loaded data in the API interface. There should be at least 10 different employee instances in the employee table.
