### ISSUE TITLE
Expose Product Data

### ISSUE THREAD

**Issue by sarawithad** [EducatedCamels/educated_camels#8]
### Task
---
To create a Product Object Class for our Database via Django REST Framework. The Objective of this task is to expose product data for the client.

### Context
---
A Product Class table is required for the integrity of the database. Please refer to ERD: 
[ERD](ERD link here)

- For more resources on this projects click [Here](https://github.com/EducatedCamels/educated_camels/blob/master/resources/resources.md)

### The process 
---
- [ ] Pull Down Bangazon Project onto your local computer and create a new git branch

-  [ ] Go to the Bangazon directory 

- [ ] Go to the API app

- [ ] Create the Prouct Class in the models.py file with the required properties.

- [ ] Create a viewset Class for the Product model in the views.py file.

-  [ ] Create a class that displays the specific attributes of the Product class in the serializers.py file 

- [ ] Add the employee class url extension "/products" in the urls.py file

### Outcome/expected behavior
---
 In all, 4 files will be changed. After these changes, the Class created will be ready to migrate using the Django REST framework. The outcome of the migrated files will expose the Employee Class that can also be linked to the other data tables in the database. 

### Other related tickets
---
- Expose Product Data
